openapi: 3.0.0
info:
  version: 1.0.0
  title: katurao API

paths:
  /articles:
    get:
      tags:
        - article
      description: >
        全ての記事を取得する
      responses:
        "200":
          # description: article response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"

  /article:
    post:
      tags:
        - article
      description: >
        記事を作成する
      parameters:
        - name: body
          description: string
          required: true
        - name: position
          description: json
          required: true
          example: { "x": 0, "y": 0 }
      responses:
        "204":
          description: no content
        "400":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /threads:
    get:
      tags:
        - thread
      description: >
        全てのスレッドを取得する
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Thread"

  /thread:
    post:
      tags:
        - thread
      description: >
        スレッドを作成する
      parameters:
        - name: title
          description: string
          required: true
        - name: body
          description: string
          required: true
        - name: position
          description: json
          required: true
          example: { "x": 0, "y": 0 }
      responses:
        "204":
          description: no content
        "400":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /thread/{thread_id}/rakugakis:
    get:
      tags:
        - rakugaki
      description: >
        特定スレッドの全てのrakugakiを取得する
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Thread_Rakugaki"

  /thread/{thread_id}/rakugaki:
    post:
      tags:
        - rakugaki
      description: >
        特定スレッド内のrakugakiを作成する
      parameters:
        - name: body
          description: string
          required: true
        - name: position
          description: json
          required: true
          example: { "x": 0, "y": 0 }
      responses:
        "204":
          description: no content
        "400":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /keijiban/rakugakis:
    get:
      tags:
        - rakugaki
      description: >
        掲示板の全てのrakugakiを取得する
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Keijiban_Rakugaki"

  /keijiban/rakugaki:
    post:
      tags:
        - rakugaki
      description: >
        掲示板にrakugakiを作成する
      parameters:
        - name: body
          description: string
          required: true
        - name: position
          description: json
          required: true
          example: { "x": 0, "y": 0 }
      responses:
        "204":
          description: no content
        "400":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Article:
      type: "object"
      properties:
        id:
          type: "integer"
          # format: "int64"
        created_at:
          type: "string"
          format: "date-time"
        body:
          type: "string"
        position:
          type: json
          example: { "x": 0, "y": 0 }

    Thread:
      type: "object"
      properties:
        id:
          type: "integer"
        title:
          type: "string"
        created_at:
          type: "string"
          format: "date-time"
        position:
          type: json
          example: { "x": 0, "y": 0 }
        thread_rakugakis:
          type: "array"
          items:
            $ref: "#/components/schemas/Thread_Rakugaki"

    Keijiban_Rakugaki:
      type: "object"
      properties:
        id:
          type: "integer"
        body:
          type: "string"
        created_at:
          type: "string"
          format: "date-time"
        position:
          type: json
          example: { "x": 0, "y": 0 }

    Thread_Rakugaki:
      type: "object"
      properties:
        id:
          type: "integer"
        thread_id:
          type: "integer"
        body:
          type: "string"
        created_at:
          type: "string"
          format: "date-time"
        position:
          type: json
          example: { "x": 0, "y": 0 }

    Error:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        message:
          type: "string"

externalDocs:
  description: "back repository"
  url: "https://github.com/wataruhigasi/Katurao-Hackathon-Back"
