// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Articles         string
	KeijibanRakugaki string
	ThreadRakugaki   string
	Threads          string
}{
	Articles:         "articles",
	KeijibanRakugaki: "keijiban_rakugaki",
	ThreadRakugaki:   "thread_rakugaki",
	Threads:          "threads",
}
