// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// KeijibanRakugaki is an object representing the database table.
type KeijibanRakugaki struct {
	ID        int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Body      string     `boil:"body" json:"body" toml:"body" yaml:"body"`
	Position  types.JSON `boil:"position" json:"position" toml:"position" yaml:"position"`
	CreatedAt time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *keijibanRakugakiR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L keijibanRakugakiL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var KeijibanRakugakiColumns = struct {
	ID        string
	Body      string
	Position  string
	CreatedAt string
}{
	ID:        "id",
	Body:      "body",
	Position:  "position",
	CreatedAt: "created_at",
}

var KeijibanRakugakiTableColumns = struct {
	ID        string
	Body      string
	Position  string
	CreatedAt string
}{
	ID:        "keijiban_rakugaki.id",
	Body:      "keijiban_rakugaki.body",
	Position:  "keijiban_rakugaki.position",
	CreatedAt: "keijiban_rakugaki.created_at",
}

// Generated where

var KeijibanRakugakiWhere = struct {
	ID        whereHelperint64
	Body      whereHelperstring
	Position  whereHelpertypes_JSON
	CreatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "`keijiban_rakugaki`.`id`"},
	Body:      whereHelperstring{field: "`keijiban_rakugaki`.`body`"},
	Position:  whereHelpertypes_JSON{field: "`keijiban_rakugaki`.`position`"},
	CreatedAt: whereHelpertime_Time{field: "`keijiban_rakugaki`.`created_at`"},
}

// KeijibanRakugakiRels is where relationship names are stored.
var KeijibanRakugakiRels = struct {
}{}

// keijibanRakugakiR is where relationships are stored.
type keijibanRakugakiR struct {
}

// NewStruct creates a new relationship struct
func (*keijibanRakugakiR) NewStruct() *keijibanRakugakiR {
	return &keijibanRakugakiR{}
}

// keijibanRakugakiL is where Load methods for each relationship are stored.
type keijibanRakugakiL struct{}

var (
	keijibanRakugakiAllColumns            = []string{"id", "body", "position", "created_at"}
	keijibanRakugakiColumnsWithoutDefault = []string{"body", "position"}
	keijibanRakugakiColumnsWithDefault    = []string{"id", "created_at"}
	keijibanRakugakiPrimaryKeyColumns     = []string{"id"}
	keijibanRakugakiGeneratedColumns      = []string{}
)

type (
	// KeijibanRakugakiSlice is an alias for a slice of pointers to KeijibanRakugaki.
	// This should almost always be used instead of []KeijibanRakugaki.
	KeijibanRakugakiSlice []*KeijibanRakugaki
	// KeijibanRakugakiHook is the signature for custom KeijibanRakugaki hook methods
	KeijibanRakugakiHook func(context.Context, boil.ContextExecutor, *KeijibanRakugaki) error

	keijibanRakugakiQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	keijibanRakugakiType                 = reflect.TypeOf(&KeijibanRakugaki{})
	keijibanRakugakiMapping              = queries.MakeStructMapping(keijibanRakugakiType)
	keijibanRakugakiPrimaryKeyMapping, _ = queries.BindMapping(keijibanRakugakiType, keijibanRakugakiMapping, keijibanRakugakiPrimaryKeyColumns)
	keijibanRakugakiInsertCacheMut       sync.RWMutex
	keijibanRakugakiInsertCache          = make(map[string]insertCache)
	keijibanRakugakiUpdateCacheMut       sync.RWMutex
	keijibanRakugakiUpdateCache          = make(map[string]updateCache)
	keijibanRakugakiUpsertCacheMut       sync.RWMutex
	keijibanRakugakiUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var keijibanRakugakiAfterSelectHooks []KeijibanRakugakiHook

var keijibanRakugakiBeforeInsertHooks []KeijibanRakugakiHook
var keijibanRakugakiAfterInsertHooks []KeijibanRakugakiHook

var keijibanRakugakiBeforeUpdateHooks []KeijibanRakugakiHook
var keijibanRakugakiAfterUpdateHooks []KeijibanRakugakiHook

var keijibanRakugakiBeforeDeleteHooks []KeijibanRakugakiHook
var keijibanRakugakiAfterDeleteHooks []KeijibanRakugakiHook

var keijibanRakugakiBeforeUpsertHooks []KeijibanRakugakiHook
var keijibanRakugakiAfterUpsertHooks []KeijibanRakugakiHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *KeijibanRakugaki) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range keijibanRakugakiAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *KeijibanRakugaki) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range keijibanRakugakiBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *KeijibanRakugaki) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range keijibanRakugakiAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *KeijibanRakugaki) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range keijibanRakugakiBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *KeijibanRakugaki) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range keijibanRakugakiAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *KeijibanRakugaki) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range keijibanRakugakiBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *KeijibanRakugaki) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range keijibanRakugakiAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *KeijibanRakugaki) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range keijibanRakugakiBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *KeijibanRakugaki) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range keijibanRakugakiAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddKeijibanRakugakiHook registers your hook function for all future operations.
func AddKeijibanRakugakiHook(hookPoint boil.HookPoint, keijibanRakugakiHook KeijibanRakugakiHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		keijibanRakugakiAfterSelectHooks = append(keijibanRakugakiAfterSelectHooks, keijibanRakugakiHook)
	case boil.BeforeInsertHook:
		keijibanRakugakiBeforeInsertHooks = append(keijibanRakugakiBeforeInsertHooks, keijibanRakugakiHook)
	case boil.AfterInsertHook:
		keijibanRakugakiAfterInsertHooks = append(keijibanRakugakiAfterInsertHooks, keijibanRakugakiHook)
	case boil.BeforeUpdateHook:
		keijibanRakugakiBeforeUpdateHooks = append(keijibanRakugakiBeforeUpdateHooks, keijibanRakugakiHook)
	case boil.AfterUpdateHook:
		keijibanRakugakiAfterUpdateHooks = append(keijibanRakugakiAfterUpdateHooks, keijibanRakugakiHook)
	case boil.BeforeDeleteHook:
		keijibanRakugakiBeforeDeleteHooks = append(keijibanRakugakiBeforeDeleteHooks, keijibanRakugakiHook)
	case boil.AfterDeleteHook:
		keijibanRakugakiAfterDeleteHooks = append(keijibanRakugakiAfterDeleteHooks, keijibanRakugakiHook)
	case boil.BeforeUpsertHook:
		keijibanRakugakiBeforeUpsertHooks = append(keijibanRakugakiBeforeUpsertHooks, keijibanRakugakiHook)
	case boil.AfterUpsertHook:
		keijibanRakugakiAfterUpsertHooks = append(keijibanRakugakiAfterUpsertHooks, keijibanRakugakiHook)
	}
}

// One returns a single keijibanRakugaki record from the query.
func (q keijibanRakugakiQuery) One(ctx context.Context, exec boil.ContextExecutor) (*KeijibanRakugaki, error) {
	o := &KeijibanRakugaki{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for keijiban_rakugaki")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all KeijibanRakugaki records from the query.
func (q keijibanRakugakiQuery) All(ctx context.Context, exec boil.ContextExecutor) (KeijibanRakugakiSlice, error) {
	var o []*KeijibanRakugaki

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to KeijibanRakugaki slice")
	}

	if len(keijibanRakugakiAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all KeijibanRakugaki records in the query.
func (q keijibanRakugakiQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count keijiban_rakugaki rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q keijibanRakugakiQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if keijiban_rakugaki exists")
	}

	return count > 0, nil
}

// KeijibanRakugakis retrieves all the records using an executor.
func KeijibanRakugakis(mods ...qm.QueryMod) keijibanRakugakiQuery {
	mods = append(mods, qm.From("`keijiban_rakugaki`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`keijiban_rakugaki`.*"})
	}

	return keijibanRakugakiQuery{q}
}

// FindKeijibanRakugaki retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindKeijibanRakugaki(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*KeijibanRakugaki, error) {
	keijibanRakugakiObj := &KeijibanRakugaki{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `keijiban_rakugaki` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, keijibanRakugakiObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from keijiban_rakugaki")
	}

	if err = keijibanRakugakiObj.doAfterSelectHooks(ctx, exec); err != nil {
		return keijibanRakugakiObj, err
	}

	return keijibanRakugakiObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *KeijibanRakugaki) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no keijiban_rakugaki provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(keijibanRakugakiColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	keijibanRakugakiInsertCacheMut.RLock()
	cache, cached := keijibanRakugakiInsertCache[key]
	keijibanRakugakiInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			keijibanRakugakiAllColumns,
			keijibanRakugakiColumnsWithDefault,
			keijibanRakugakiColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(keijibanRakugakiType, keijibanRakugakiMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(keijibanRakugakiType, keijibanRakugakiMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `keijiban_rakugaki` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `keijiban_rakugaki` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `keijiban_rakugaki` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, keijibanRakugakiPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into keijiban_rakugaki")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == keijibanRakugakiMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for keijiban_rakugaki")
	}

CacheNoHooks:
	if !cached {
		keijibanRakugakiInsertCacheMut.Lock()
		keijibanRakugakiInsertCache[key] = cache
		keijibanRakugakiInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the KeijibanRakugaki.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *KeijibanRakugaki) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	keijibanRakugakiUpdateCacheMut.RLock()
	cache, cached := keijibanRakugakiUpdateCache[key]
	keijibanRakugakiUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			keijibanRakugakiAllColumns,
			keijibanRakugakiPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update keijiban_rakugaki, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `keijiban_rakugaki` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, keijibanRakugakiPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(keijibanRakugakiType, keijibanRakugakiMapping, append(wl, keijibanRakugakiPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update keijiban_rakugaki row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for keijiban_rakugaki")
	}

	if !cached {
		keijibanRakugakiUpdateCacheMut.Lock()
		keijibanRakugakiUpdateCache[key] = cache
		keijibanRakugakiUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q keijibanRakugakiQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for keijiban_rakugaki")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for keijiban_rakugaki")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o KeijibanRakugakiSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keijibanRakugakiPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `keijiban_rakugaki` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, keijibanRakugakiPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in keijibanRakugaki slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all keijibanRakugaki")
	}
	return rowsAff, nil
}

var mySQLKeijibanRakugakiUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *KeijibanRakugaki) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no keijiban_rakugaki provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(keijibanRakugakiColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLKeijibanRakugakiUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	keijibanRakugakiUpsertCacheMut.RLock()
	cache, cached := keijibanRakugakiUpsertCache[key]
	keijibanRakugakiUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			keijibanRakugakiAllColumns,
			keijibanRakugakiColumnsWithDefault,
			keijibanRakugakiColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			keijibanRakugakiAllColumns,
			keijibanRakugakiPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert keijiban_rakugaki, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`keijiban_rakugaki`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `keijiban_rakugaki` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(keijibanRakugakiType, keijibanRakugakiMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(keijibanRakugakiType, keijibanRakugakiMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for keijiban_rakugaki")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == keijibanRakugakiMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(keijibanRakugakiType, keijibanRakugakiMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for keijiban_rakugaki")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for keijiban_rakugaki")
	}

CacheNoHooks:
	if !cached {
		keijibanRakugakiUpsertCacheMut.Lock()
		keijibanRakugakiUpsertCache[key] = cache
		keijibanRakugakiUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single KeijibanRakugaki record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *KeijibanRakugaki) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no KeijibanRakugaki provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), keijibanRakugakiPrimaryKeyMapping)
	sql := "DELETE FROM `keijiban_rakugaki` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from keijiban_rakugaki")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for keijiban_rakugaki")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q keijibanRakugakiQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no keijibanRakugakiQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from keijiban_rakugaki")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for keijiban_rakugaki")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o KeijibanRakugakiSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(keijibanRakugakiBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keijibanRakugakiPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `keijiban_rakugaki` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, keijibanRakugakiPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from keijibanRakugaki slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for keijiban_rakugaki")
	}

	if len(keijibanRakugakiAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *KeijibanRakugaki) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindKeijibanRakugaki(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *KeijibanRakugakiSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := KeijibanRakugakiSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keijibanRakugakiPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `keijiban_rakugaki`.* FROM `keijiban_rakugaki` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, keijibanRakugakiPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in KeijibanRakugakiSlice")
	}

	*o = slice

	return nil
}

// KeijibanRakugakiExists checks if the KeijibanRakugaki row exists.
func KeijibanRakugakiExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `keijiban_rakugaki` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if keijiban_rakugaki exists")
	}

	return exists, nil
}

// Exists checks if the KeijibanRakugaki row exists.
func (o *KeijibanRakugaki) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return KeijibanRakugakiExists(ctx, exec, o.ID)
}
