// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Articles", testArticlesUpsert)

	t.Run("Comments", testCommentsUpsert)

	t.Run("KeijibanRakugakis", testKeijibanRakugakisUpsert)

	t.Run("ThreadRakugakis", testThreadRakugakisUpsert)

	t.Run("Threads", testThreadsUpsert)
}
