// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testThreadRakugakis(t *testing.T) {
	t.Parallel()

	query := ThreadRakugakis()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testThreadRakugakisDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ThreadRakugakis().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testThreadRakugakisQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ThreadRakugakis().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ThreadRakugakis().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testThreadRakugakisSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ThreadRakugakiSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ThreadRakugakis().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testThreadRakugakisExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ThreadRakugakiExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ThreadRakugaki exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ThreadRakugakiExists to return true, but got false.")
	}
}

func testThreadRakugakisFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	threadRakugakiFound, err := FindThreadRakugaki(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if threadRakugakiFound == nil {
		t.Error("want a record, got nil")
	}
}

func testThreadRakugakisBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ThreadRakugakis().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testThreadRakugakisOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ThreadRakugakis().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testThreadRakugakisAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	threadRakugakiOne := &ThreadRakugaki{}
	threadRakugakiTwo := &ThreadRakugaki{}
	if err = randomize.Struct(seed, threadRakugakiOne, threadRakugakiDBTypes, false, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}
	if err = randomize.Struct(seed, threadRakugakiTwo, threadRakugakiDBTypes, false, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = threadRakugakiOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = threadRakugakiTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ThreadRakugakis().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testThreadRakugakisCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	threadRakugakiOne := &ThreadRakugaki{}
	threadRakugakiTwo := &ThreadRakugaki{}
	if err = randomize.Struct(seed, threadRakugakiOne, threadRakugakiDBTypes, false, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}
	if err = randomize.Struct(seed, threadRakugakiTwo, threadRakugakiDBTypes, false, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = threadRakugakiOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = threadRakugakiTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ThreadRakugakis().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func threadRakugakiBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ThreadRakugaki) error {
	*o = ThreadRakugaki{}
	return nil
}

func threadRakugakiAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ThreadRakugaki) error {
	*o = ThreadRakugaki{}
	return nil
}

func threadRakugakiAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ThreadRakugaki) error {
	*o = ThreadRakugaki{}
	return nil
}

func threadRakugakiBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ThreadRakugaki) error {
	*o = ThreadRakugaki{}
	return nil
}

func threadRakugakiAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ThreadRakugaki) error {
	*o = ThreadRakugaki{}
	return nil
}

func threadRakugakiBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ThreadRakugaki) error {
	*o = ThreadRakugaki{}
	return nil
}

func threadRakugakiAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ThreadRakugaki) error {
	*o = ThreadRakugaki{}
	return nil
}

func threadRakugakiBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ThreadRakugaki) error {
	*o = ThreadRakugaki{}
	return nil
}

func threadRakugakiAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ThreadRakugaki) error {
	*o = ThreadRakugaki{}
	return nil
}

func testThreadRakugakisHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ThreadRakugaki{}
	o := &ThreadRakugaki{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki object: %s", err)
	}

	AddThreadRakugakiHook(boil.BeforeInsertHook, threadRakugakiBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	threadRakugakiBeforeInsertHooks = []ThreadRakugakiHook{}

	AddThreadRakugakiHook(boil.AfterInsertHook, threadRakugakiAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	threadRakugakiAfterInsertHooks = []ThreadRakugakiHook{}

	AddThreadRakugakiHook(boil.AfterSelectHook, threadRakugakiAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	threadRakugakiAfterSelectHooks = []ThreadRakugakiHook{}

	AddThreadRakugakiHook(boil.BeforeUpdateHook, threadRakugakiBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	threadRakugakiBeforeUpdateHooks = []ThreadRakugakiHook{}

	AddThreadRakugakiHook(boil.AfterUpdateHook, threadRakugakiAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	threadRakugakiAfterUpdateHooks = []ThreadRakugakiHook{}

	AddThreadRakugakiHook(boil.BeforeDeleteHook, threadRakugakiBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	threadRakugakiBeforeDeleteHooks = []ThreadRakugakiHook{}

	AddThreadRakugakiHook(boil.AfterDeleteHook, threadRakugakiAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	threadRakugakiAfterDeleteHooks = []ThreadRakugakiHook{}

	AddThreadRakugakiHook(boil.BeforeUpsertHook, threadRakugakiBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	threadRakugakiBeforeUpsertHooks = []ThreadRakugakiHook{}

	AddThreadRakugakiHook(boil.AfterUpsertHook, threadRakugakiAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	threadRakugakiAfterUpsertHooks = []ThreadRakugakiHook{}
}

func testThreadRakugakisInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ThreadRakugakis().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testThreadRakugakisInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(threadRakugakiColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ThreadRakugakis().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testThreadRakugakisReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testThreadRakugakisReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ThreadRakugakiSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testThreadRakugakisSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ThreadRakugakis().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	threadRakugakiDBTypes = map[string]string{`ID`: `bigint`, `ThreadID`: `bigint`, `Body`: `varchar`, `Position`: `json`, `CreatedAt`: `datetime`}
	_                     = bytes.MinRead
)

func testThreadRakugakisUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(threadRakugakiPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(threadRakugakiAllColumns) == len(threadRakugakiPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ThreadRakugakis().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testThreadRakugakisSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(threadRakugakiAllColumns) == len(threadRakugakiPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ThreadRakugaki{}
	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ThreadRakugakis().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, threadRakugakiDBTypes, true, threadRakugakiPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(threadRakugakiAllColumns, threadRakugakiPrimaryKeyColumns) {
		fields = threadRakugakiAllColumns
	} else {
		fields = strmangle.SetComplement(
			threadRakugakiAllColumns,
			threadRakugakiPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ThreadRakugakiSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testThreadRakugakisUpsert(t *testing.T) {
	t.Parallel()

	if len(threadRakugakiAllColumns) == len(threadRakugakiPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLThreadRakugakiUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ThreadRakugaki{}
	if err = randomize.Struct(seed, &o, threadRakugakiDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ThreadRakugaki: %s", err)
	}

	count, err := ThreadRakugakis().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, threadRakugakiDBTypes, false, threadRakugakiPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ThreadRakugaki struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ThreadRakugaki: %s", err)
	}

	count, err = ThreadRakugakis().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
