// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testThreads(t *testing.T) {
	t.Parallel()

	query := Threads()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testThreadsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Threads().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testThreadsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Threads().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Threads().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testThreadsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ThreadSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Threads().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testThreadsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ThreadExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Thread exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ThreadExists to return true, but got false.")
	}
}

func testThreadsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	threadFound, err := FindThread(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if threadFound == nil {
		t.Error("want a record, got nil")
	}
}

func testThreadsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Threads().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testThreadsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Threads().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testThreadsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	threadOne := &Thread{}
	threadTwo := &Thread{}
	if err = randomize.Struct(seed, threadOne, threadDBTypes, false, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}
	if err = randomize.Struct(seed, threadTwo, threadDBTypes, false, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = threadOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = threadTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Threads().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testThreadsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	threadOne := &Thread{}
	threadTwo := &Thread{}
	if err = randomize.Struct(seed, threadOne, threadDBTypes, false, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}
	if err = randomize.Struct(seed, threadTwo, threadDBTypes, false, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = threadOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = threadTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Threads().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func threadBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Thread) error {
	*o = Thread{}
	return nil
}

func threadAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Thread) error {
	*o = Thread{}
	return nil
}

func threadAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Thread) error {
	*o = Thread{}
	return nil
}

func threadBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Thread) error {
	*o = Thread{}
	return nil
}

func threadAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Thread) error {
	*o = Thread{}
	return nil
}

func threadBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Thread) error {
	*o = Thread{}
	return nil
}

func threadAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Thread) error {
	*o = Thread{}
	return nil
}

func threadBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Thread) error {
	*o = Thread{}
	return nil
}

func threadAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Thread) error {
	*o = Thread{}
	return nil
}

func testThreadsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Thread{}
	o := &Thread{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, threadDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Thread object: %s", err)
	}

	AddThreadHook(boil.BeforeInsertHook, threadBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	threadBeforeInsertHooks = []ThreadHook{}

	AddThreadHook(boil.AfterInsertHook, threadAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	threadAfterInsertHooks = []ThreadHook{}

	AddThreadHook(boil.AfterSelectHook, threadAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	threadAfterSelectHooks = []ThreadHook{}

	AddThreadHook(boil.BeforeUpdateHook, threadBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	threadBeforeUpdateHooks = []ThreadHook{}

	AddThreadHook(boil.AfterUpdateHook, threadAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	threadAfterUpdateHooks = []ThreadHook{}

	AddThreadHook(boil.BeforeDeleteHook, threadBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	threadBeforeDeleteHooks = []ThreadHook{}

	AddThreadHook(boil.AfterDeleteHook, threadAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	threadAfterDeleteHooks = []ThreadHook{}

	AddThreadHook(boil.BeforeUpsertHook, threadBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	threadBeforeUpsertHooks = []ThreadHook{}

	AddThreadHook(boil.AfterUpsertHook, threadAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	threadAfterUpsertHooks = []ThreadHook{}
}

func testThreadsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Threads().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testThreadsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(threadColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Threads().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testThreadsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testThreadsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ThreadSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testThreadsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Threads().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	threadDBTypes = map[string]string{`ID`: `bigint`, `Title`: `varchar`, `Position`: `json`, `CreatedAt`: `datetime`}
	_             = bytes.MinRead
)

func testThreadsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(threadPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(threadAllColumns) == len(threadPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Threads().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, threadDBTypes, true, threadPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testThreadsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(threadAllColumns) == len(threadPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Thread{}
	if err = randomize.Struct(seed, o, threadDBTypes, true, threadColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Threads().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, threadDBTypes, true, threadPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(threadAllColumns, threadPrimaryKeyColumns) {
		fields = threadAllColumns
	} else {
		fields = strmangle.SetComplement(
			threadAllColumns,
			threadPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ThreadSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testThreadsUpsert(t *testing.T) {
	t.Parallel()

	if len(threadAllColumns) == len(threadPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLThreadUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Thread{}
	if err = randomize.Struct(seed, &o, threadDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Thread: %s", err)
	}

	count, err := Threads().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, threadDBTypes, false, threadPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Thread struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Thread: %s", err)
	}

	count, err = Threads().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
